// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheTourMinsaitVersaoFinal.Data;

#nullable disable

namespace TheTourMinsaitVersaoFinal.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20221115215125_ID9b")]
    partial class ID9b
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TheTourMinsaitVersaoFinal.Models.Bairro", b =>
                {
                    b.Property<Guid>("BairroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BairroNome")
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext");

                    b.HasKey("BairroId");

                    b.ToTable("Bairros");
                });
#pragma warning restore 612, 618
        }
    }
}
