// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheTourMinsaitVersaoFinal.Data;

#nullable disable

namespace TheTourMinsaitVersaoFinal.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20221116015835_PASSEIOS")]
    partial class PASSEIOS
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TheTourMinsaitVersaoFinal.Models.Bairro", b =>
                {
                    b.Property<Guid>("BairroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BairroNome")
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext");

                    b.HasKey("BairroId");

                    b.ToTable("Bairros");
                });

            modelBuilder.Entity("TheTourMinsaitVersaoFinal.Models.Passeio", b =>
                {
                    b.Property<Guid>("PasseioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("GuiaFalaIngles")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasseioDescricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasseioGuia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasseioNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QuantidadeDePessoas")
                        .HasColumnType("int");

                    b.Property<double>("ValorCobradoPasseio")
                        .HasColumnType("double");

                    b.HasKey("PasseioId");

                    b.ToTable("Passeios");
                });
#pragma warning restore 612, 618
        }
    }
}
