// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheTourMinsaitVersaoFinal.Data;

#nullable disable

namespace TheTourMinsaitVersaoFinal.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TheTourMinsaitVersaoFinal.Models.Bairro", b =>
                {
                    b.Property<Guid>("BairroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BairroNome")
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext");

                    b.HasKey("BairroId");

                    b.ToTable("Bairros");
                });

            modelBuilder.Entity("TheTourMinsaitVersaoFinal.Models.Passeio", b =>
                {
                    b.Property<Guid>("PasseioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("GuiaFalaIngles")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasseioDescricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasseioGuia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasseioNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("QuantidadeDePessoas")
                        .HasColumnType("int");

                    b.Property<double>("ValorCobradoPasseio")
                        .HasColumnType("double");

                    b.HasKey("PasseioId");

                    b.ToTable("Passeios");
                });

            modelBuilder.Entity("TheTourMinsaitVersaoFinal.Models.PontoTuristico", b =>
                {
                    b.Property<Guid>("PontoTuristicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("CobrancaDeEntrada")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PontoTuristicoHorarioDeFuncionamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PontoTuristicoLocalidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PontoTuristicoNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PontoTuristicoObservacoes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PontoTuristicoId");

                    b.ToTable("PontosTuristicos");
                });

            modelBuilder.Entity("TheTourMinsaitVersaoFinal.Models.Praia", b =>
                {
                    b.Property<Guid>("PraiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("PraiaLocalidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PraiaNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PraiaObservacoes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PraiaId");

                    b.ToTable("Praias");
                });

            modelBuilder.Entity("TheTourMinsaitVersaoFinal.Models.Restaurante", b =>
                {
                    b.Property<Guid>("RestauranteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("RestauranteAvaliacaoMedia")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RestauranteDescricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RestauranteHorarioFuncionamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RestauranteLocalizacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RestauranteNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RestauranteId");

                    b.ToTable("Restaurantes");
                });

            modelBuilder.Entity("TheTourMinsaitVersaoFinal.Models.VidaNoturna", b =>
                {
                    b.Property<Guid>("VidaNoturnaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("VidaNoturnaHorarioFuncionamento")
                        .HasColumnType("double");

                    b.Property<string>("VidaNoturnaNome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("VidaNoturnaTipoLocal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("VidaNoturnaValorDaEntrada")
                        .HasColumnType("double");

                    b.HasKey("VidaNoturnaId");

                    b.ToTable("VidaNoturnas");
                });
#pragma warning restore 612, 618
        }
    }
}
